

IF DB_ID('FACETSCD') IS NOT NULL
BEGIN
	ALTER DATABASE   [FACETSCD] SET SINGLE_USER WITH ROLLBACK IMMEDIATE

RESTORE DATABASE [FACETSCD] FROM  DISK = N'I:\BuildBackups\SQLFACT\FACETSCD.bak' 
	WITH  FILE = 1
	,  MOVE 'FACETSCD'     TO 'F:\MSSQL12.LATBIN14\MSSQL\Data\FACETSCD.mdf'
	,  MOVE 'FACETSCD_log' TO 'G:\MSSQL12.LATBIN14\MSSQL\TLog\FACETSCD_log.ldf'
	,  NOUNLOAD,  REPLACE
end
	
ALTER DATABASE   [FACETSCD] SET MULTI_USER
GO